name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.11', '3.12']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
          ~/.virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Dependencies
      run: |
        poetry config virtualenvs.create true
        poetry install --no-interaction --no-ansi
      env:
        POETRY_HTTP_TIMEOUT: 600
        POETRY_VIRTUALENVS_IN_PROJECT: false
        PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    
    - name: Run Tests
      run: poetry run nox -s tests-${{ matrix.python }}

    - name: Lint
      run: poetry run nox -s lint